// Human labels for scripts and languages, generated by the harvester
// (to_dataset.py write_label_maps) from gflanguages, so the frontend renders
// readable names without shipping gftools. See the language-support task.
import languagesRaw from "@/data/languages.json";
import scriptsRaw from "@/data/scripts.json";

export interface LanguageMeta {
  name: string;
  script: string;
  population: number;
  region: string;
}

// Continent buckets in the order Google Fonts lists them; "Other" (languages
// with no CLDR region) trails at the end when present.
export const LANGUAGE_REGIONS = [
  "Africa",
  "Americas",
  "Asia",
  "Europe",
  "Oceania",
  "Other",
] as const;

const scripts = scriptsRaw as Record<string, string>;
const languages = languagesRaw as Record<string, LanguageMeta>;

// Google Fonts' website shows a curated MAJOR-language subset; population>=5M
// reproduces it cleanly. The UI defaults to these, with a "show all" expander.
export const MAJOR_LANG_POPULATION = 5_000_000;

/** "Latn" -> "Latin"; unknown codes pass through unchanged. */
export function scriptLabel(code: string): string {
  return scripts[code] ?? code;
}

/** "en_Latn" -> "English"; unknown ids pass through unchanged. */
export function languageLabel(id: string): string {
  return languages[id]?.name ?? id;
}

export function languagePopulation(id: string): number {
  return languages[id]?.population ?? 0;
}

export function languageRegion(id: string): string {
  return languages[id]?.region ?? "Other";
}

/** Bucket lang ids by continent, each name-sorted, in LANGUAGE_REGIONS order.
 *  Only non-empty regions are returned. */
export function groupLanguagesByRegion(
  ids: string[]
): { region: string; ids: string[] }[] {
  const byRegion = new Map<string, string[]>();
  for (const id of ids) {
    const r = languageRegion(id);
    const bucket = byRegion.get(r);
    if (bucket) bucket.push(id);
    else byRegion.set(r, [id]);
  }
  const byName = (a: string, b: string) =>
    languageLabel(a).localeCompare(languageLabel(b));
  return LANGUAGE_REGIONS.filter((r) => byRegion.has(r)).map((region) => ({
    region,
    ids: (byRegion.get(region) as string[]).sort(byName),
  }));
}

// Script -> total speaker population, summed from every language written in
// it (gflanguages), so Writing system pills can rank by real-world reach
// instead of how many fonts happen to declare that subset.
const SCRIPT_POPULATION: Record<string, number> = {};
for (const meta of Object.values(languages)) {
  if (!meta.script) continue;
  SCRIPT_POPULATION[meta.script] =
    (SCRIPT_POPULATION[meta.script] ?? 0) + (meta.population ?? 0);
}

export function scriptPopulation(code: string): number {
  return SCRIPT_POPULATION[code] ?? 0;
}

/** Split lang ids into major (>=5M speakers) and the rest, each name-sorted. */
export function splitLanguages(ids: string[]): {
  major: string[];
  minor: string[];
} {
  const major: string[] = [];
  const minor: string[] = [];
  for (const id of ids) {
    if (languagePopulation(id) >= MAJOR_LANG_POPULATION) major.push(id);
    else minor.push(id);
  }
  const byName = (a: string, b: string) =>
    languageLabel(a).localeCompare(languageLabel(b));
  return { major: major.sort(byName), minor: minor.sort(byName) };
}
