/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FontIdRouteRouteImport } from './routes/$fontId/route'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as TabFontIdRouteRouteImport } from './routes/$tab.$fontId/route'

const FontIdRouteRoute = FontIdRouteRouteImport.update({
  id: '/$fontId',
  path: '/$fontId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const TabFontIdRouteRoute = TabFontIdRouteRouteImport.update({
  id: '/$tab/$fontId',
  path: '/$tab/$fontId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/$fontId': typeof FontIdRouteRoute
  '/$tab/$fontId': typeof TabFontIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/$fontId': typeof FontIdRouteRoute
  '/$tab/$fontId': typeof TabFontIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/$fontId': typeof FontIdRouteRoute
  '/$tab/$fontId': typeof TabFontIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$fontId' | '/$tab/$fontId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$fontId' | '/$tab/$fontId'
  id: '__root__' | '/' | '/$fontId' | '/$tab/$fontId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  FontIdRouteRoute: typeof FontIdRouteRoute
  TabFontIdRouteRoute: typeof TabFontIdRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$fontId': {
      id: '/$fontId'
      path: '/$fontId'
      fullPath: '/$fontId'
      preLoaderRoute: typeof FontIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tab/$fontId': {
      id: '/$tab/$fontId'
      path: '/$tab/$fontId'
      fullPath: '/$tab/$fontId'
      preLoaderRoute: typeof TabFontIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  FontIdRouteRoute: FontIdRouteRoute,
  TabFontIdRouteRoute: TabFontIdRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
