/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FontIdRouteImport } from './routes/$fontId'
import { Route as IndexRouteImport } from './routes/index'

const FontIdRoute = FontIdRouteImport.update({
  id: '/$fontId',
  path: '/$fontId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$fontId': typeof FontIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$fontId': typeof FontIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$fontId': typeof FontIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$fontId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$fontId'
  id: '__root__' | '/' | '/$fontId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FontIdRoute: typeof FontIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$fontId': {
      id: '/$fontId'
      path: '/$fontId'
      fullPath: '/$fontId'
      preLoaderRoute: typeof FontIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FontIdRoute: FontIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
